server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    additional-tld-skip-patterns: "*.jar"


spring:      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intimeDB?serverTimezone=Asia/Seoul #jdbc:mysql://localhost:3306/intimedb_local?serverTimezone=Asia/Seoul
    username: intime
    password: intime123

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true #console에 sql 출력
    properties:
      hibernate.format_sql: false #console에 sql 출력시 깔끔하게 정렬되서 출력

  jackson:
    serialization:
      fail-on-empty-beans: false

  redis:
    host: redisc-dr2ie.vpc-cdb.ntruss.com
    port: 6379

jwt:
  secretKey: intime123
  expiration-milliseconds: 60000000 #10분


